plugins:
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"

Layout/LineLength:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/HashAlignment:
  EnforcedColonStyle:
    - table
    - key
  EnforcedHashRocketStyle:
    - table
    - key

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Max: 500
  Exclude:
    - "test/**/*"

Metrics/BlockLength:
  Max: 100
  Exclude:
    - "*.gemspec"
    - "Rakefile"

Metrics/ClassLength:
  Max: 500
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  Max: 200
  Exclude:
    - "test/**/*"

Metrics/ModuleLength:
  Max: 500
  Exclude:
    - "test/**/*"

Metrics/ParameterLists:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 50

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rake/Desc:
  Enabled: false

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrivialAccessors:
  AllowPredicates: true
